import { useState } from "react";

export type SurroundViewCase = {
  key: string;
  label: string;
  summary: string;
  vectorSrc: string;
  layoutSrc: string;
  resultSrc: string;
};

type Props = {
  cases: SurroundViewCase[];
};

type Tone = "zinc" | "blue" | "violet";

type StageCardProps = {
  title: string;
  badge: string;
  caption: string;
  src: string;
  tone: Tone;
  colSpan: string;
};

const selectedPillClass =
  "rounded-full border border-[color:var(--vw-accent-line)] bg-brand-soft px-4 py-2 text-sm font-medium text-brand transition";

const inactivePillClass =
  "rounded-full border border-hairline-strong px-4 py-2 text-sm font-medium text-ink-2 transition hover:border-[color:var(--vw-accent-line)] hover:text-ink-1 active:scale-[0.98]";

// "blue" marks the single accented stage (the vector-to-sensor bridge);
// every other stage stays neutral so the page keeps one brand color.
function sectionToneClass(tone: Tone) {
  return tone === "blue"
    ? "border-[color:var(--vw-accent-line)] bg-brand-soft"
    : "border-hairline bg-surface-2";
}

function badgeToneClass(tone: Tone) {
  return tone === "blue"
    ? "bg-brand-soft text-brand"
    : "bg-surface-3 text-ink-2";
}

function StageCard({ title, badge, caption, src, tone, colSpan }: StageCardProps) {
  return (
    <section className={`${colSpan} rounded-2xl border p-4 ${sectionToneClass(tone)}`}>
      <div className="mb-3 flex items-center justify-between gap-3">
        <p className="text-sm font-semibold text-ink-1">{title}</p>
        <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${badgeToneClass(tone)}`}>{badge}</span>
      </div>
      <div className="overflow-hidden rounded-2xl border border-hairline bg-[var(--vw-canvas)]">
        <div className="flex h-52 items-center justify-center md:h-60 xl:h-72">
          <video src={src} controls muted playsInline preload="metadata" className="h-full w-full object-contain" />
        </div>
      </div>
      <p className="mt-3 text-sm leading-6 text-ink-2">{caption}</p>
    </section>
  );
}

export default function SurroundViewCaseSliderClient({ cases }: Props) {
  const [index, setIndex] = useState(0);
  if (cases.length === 0) return null;
  const current = cases[index] ?? cases[0];

  const goPrev = () => setIndex((c) => (c === 0 ? cases.length - 1 : c - 1));
  const goNext = () => setIndex((c) => (c === cases.length - 1 ? 0 : c + 1));

  return (
    <div className="space-y-5">
      <section className="rounded-3xl border border-hairline bg-surface-1 p-5">
        <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">
          <div className="space-y-3">
            <div>
              <p className="mb-3 text-sm font-medium text-ink-2">Cases</p>
              <div className="flex flex-wrap gap-2">
                {cases.map((item, i) => (
                  <button key={item.key} type="button" onClick={() => setIndex(i)}
                    className={i === index ? selectedPillClass : inactivePillClass}>
                    {item.label}
                  </button>
                ))}
              </div>
            </div>

            <div className="flex flex-wrap gap-2">
              <button type="button" onClick={goPrev} className={inactivePillClass}>← Previous</button>
              <button type="button" onClick={goNext} className={inactivePillClass}>Next →</button>
              <span className="rounded-full border border-hairline-strong bg-surface-1 px-4 py-2 text-sm font-medium text-ink-2">
                {current.label} · {index + 1} / {cases.length}
              </span>
            </div>
          </div>

          <div className="max-w-3xl rounded-2xl border border-[color:var(--vw-accent-line)] bg-brand-soft p-4">
            <p className="vw-eyebrow">Vector-to-sensor bridge</p>
            <p className="mt-2 text-sm leading-6 text-ink-2">
              VectorWorld supplies an explicit vector-world prior. After projection into image space, a downstream video model can generate sensor-level surround-view videos with stronger geometry, motion, and interaction consistency for autonomous driving.
            </p>
          </div>
        </div>
      </section>

      <div className="grid gap-4 xl:grid-cols-12">
        <StageCard title="Stage 1 · Vector world" badge="World prior" caption="Explicit vector scene generated by VectorWorld." src={current.vectorSrc} tone="zinc" colSpan="xl:col-span-3" />
        <StageCard title="Stage 2 · Sensor-space projection" badge="Bridge" caption="Projection that exposes the structural prior in image space." src={current.layoutSrc} tone="blue" colSpan="xl:col-span-4" />
        <StageCard title="Stage 3 · Sensor-level video" badge="Video model" caption="Surround-view video conditioned on the projected structural prior." src={current.resultSrc} tone="zinc" colSpan="xl:col-span-5" />
      </div>

      <div className="rounded-3xl border border-hairline bg-surface-2 p-4 text-sm leading-6 text-ink-2">
        <strong className="text-ink-1">Takeaway.</strong>{" "}
        Vector scene → projected layout → sensor-level video. The vector world model keeps structure explicit, and the video model lifts it to a more physical, controllable surround-view world.
      </div>
    </div>
  );
}
